### ISSUE TITLE
Update Usage instructions

### ISSUE THREAD

**Issue by balibebas** [outgrow/reaction-file-collections-sa-s3#6]
`setUpFileCollections` moved to `api-plugin-files`. As a result, the current usage instructions are out of date.

**Comment by mian-muhammad** [comment]
> `setUpFileCollections` moved to `api-plugin-files`. As a result, the current usage instructions are out of date.

@balibebas any recommendations to use it with newer versions of reaction api?

**Comment by balibebas** [comment]
At the moment only some hacky code 😅

**Comment by mian-muhammad** [comment]
@balibebas could you share that hacky code, I need that :D

**Comment by balibebas** [comment]
If I forget please ping me on Telegram and I'll send it over to you. Contact information on my website.

**Comment by loan-laux** [comment]
@balibebas @mian-muhammad Sorry for taking so long on this. The README is now up to date!
